---
- name: Create redosvms
  hosts: localhost

  vars_files:
  # Contains encrypted `engine_password` varibale using ansible-vault
    - zvirt.yml
    - createvms-zvirt.yml

  pre_tasks:
    - name: Login
      ovirt.ovirt.ovirt_auth:
        url: "https://{{ engine_fqdn }}/ovirt-engine/api"
        password: "{{ engine_password }}"
        username: "{{ engine_user }}"
        ca_file: "{{ engine_cafile }}"

  post_tasks:
    - name: Logoff
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"

  tasks:
    - name: Start VM
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ newvm.name | default(newvm.project + '_' + newvm.site + newvm.role + newvm.suffix | string) }}"
        state: running
        wait: true
      loop: "{{ newvms }}"
      loop_control:
        loop_var: newvm
