# vars:
cidisable_disabled_services:
  - cloud-config.service
  - cloud-final.service
  - cloud-init-local.service
  - cloud-init.service
cidisable_remove_files:
  - /etc/network/interfaces.d/50-cloud-init
