- name: Preconfig disable cloud-init
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Disable and stop services
      ansible.builtin.service:
        name: "{{ service }}"
        state: stopped
        enabled: false
      loop: "{{ cloudintidisable_services }}"
      loop_control:
        loop_var: service
      when:
        - ansible_facts.services[service] is defined
        - ansible_facts.services[service].status == "enabled"

    - name: Check if /etc/cloud/ exists
      ansible.builtin.stat:
        path: /etc/cloud/
      register: etc_cloud_folder

    - name: Generate /etc/cloud/cloud-init.disabled
      ansible.builtin.copy:
        dest: /etc/cloud/cloud-init.disabled
        content: 'disabled by ansible\n'
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - etc_cloud_folder.stat.exists
