ansible_connection: ansible.netcommon.network_cli
ansible_network_os: community.routeros.routeros
ansible_user: croc
# ansible_ssh_pass: QAZxsw123
# ansible_become: true
# ansible_become_method: enable
# ansible_become_password: QAZxsw123
# ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'
