---
- name: Delete VMs proxmox
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - proxmox.yml
    - createvms-proxmox.yml
  pre_tasks:
    - debug:
        var: deletevms

  tasks:
    - name: Delete VMs
      block: 
        - name: Stop VMs
          community.general.proxmox_kvm:
            state: stopped
            force: true
            api_user: "{{ proxmox.api_user }}"
            api_password: "{{ proxmox.api_password }}"
            api_token_id: "{{ proxmox.api_token_id }}"
            api_token_secret: "{{ proxmox.api_token_secret }}"
            api_host: "{{ proxmox.api_host }}"
            name: "{{ newvm.name | default(newvm.site + newvm.role + newvm.suffix|default(omit)) }}"
            node: "{{ newvm.node | default(proxmox.node) }}"
          loop: "{{ createvm_proxmox }}"
          loop_control:
            loop_var: newvm
          ignore_errors: true
        - name: Delete VMs
          community.general.proxmox_kvm:
            force: true
            state: absent
            api_user: "{{ proxmox.api_user }}"
            api_password: "{{ proxmox.api_password }}"
            api_token_id: "{{ proxmox.api_token_id }}"
            api_token_secret: "{{ proxmox.api_token_secret }}"
            api_host: "{{ proxmox.api_host }}"
            name: "{{ newvm.name | default(newvm.site + newvm.role + newvm.suffix|default(omit)) }}"
            node: "{{ newvm.node | default(proxmox.node) }}"
          loop: "{{ createvm_proxmox }}"
          loop_control:
            loop_var: newvm
      when: deletevms
