---
- name: Create a template from qcow
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - zvirt.yml
  vars:
    # engine_fqdn: ovirt-engine.example.com
    # engine_user: admin@internal
    # engine_password: 123456
    # engine_cafile: /etc/pki/ovirt-engine/ca.pem

    #qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    qcow_url: file:///mnt/d/vm/_tmp/tmp-alt-p11-min.qcow2
    template_cluster: CL-OVN
    template_name: aratner_testtmp1
    template_memory: 1GiB
    template_cpu: 2
    template_disk_size: 7GiB
    template_disk_storage: fc_dc_ovn_01

  roles:
    - image_template
  collections:
    - ovirt.ovirt
