---
- name: Preconfig firstdc
  become: true
  hosts: first_dc
  roles:
    - general

  handlers:
    - name: Restart bind9 service
      service:
        name: bind9-pkcs11
        state: restarted

  tasks: 
    - name: Allow query cache
      ansible.builtin.lineinfile:
        path: /etc/bind/ipa-options-ext.conf
        regexp: '^allow-query-cache'
        insertafter: EOF
        line: 'allow-query-cache { any; };'
      notify: Restart bind9 service

    - name: Allow recursion
      ansible.builtin.lineinfile:
        path: /etc/bind/ipa-options-ext.conf
        regexp: '^allow-recursion'
        insertafter: EOF
        line: 'allow-recursion { any; };'
      notify: Restart bind9 service

    - name: Disable dnssec-validation
      ansible.builtin.lineinfile:
        path: /etc/bind/ipa-options-ext.conf
        regexp: '^dnssec-validation'
        insertafter: EOF
        line: 'dnssec-validation no;'
      notify: Restart bind9 service

    - name: Add dns forwarder
      ansible.builtin.shell: |
        echo '{{ domain_password }}' | /usr/bin/kinit {{ domain_admin }}
        /usr/bin/ipa dnsconfig-mod --forwarder={{ domain_forwarder }} --forward-policy='first'
        /usr/bin/kdestroy -A
      when: domain_forwarder is defined
      notify: Restart bind9 service
