---
- name: Create redosvms
  hosts: localhost

  vars_files:
  # Contains encrypted `engine_password` varibale using ansible-vault
    - zvirt.yml
    - createvms-zvirt.yml

  pre_tasks:
    - name: Login
      ovirt.ovirt.ovirt_auth:
        url: "https://{{ engine_fqdn }}/ovirt-engine/api"
        password: "{{ engine_password }}"
        username: "{{ engine_user }}"
        ca_file: "{{ engine_cafile }}"

  post_tasks:
    - name: Logoff
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"

  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: createvm-zvirt
      vars:
        createvm:
          timezone: "{{ newvm.timezone | default(createvm_default.timezone) }}"
          clone: false
          startvm: false
          template_version: 0
          waitstart: false
          disksize: "{{ newvm.disksize | default('32GiB') }}"
          name: "{{ newvm.name | default(newvm.project + '_' + newvm.site + newvm.role + newvm.suffix | string) }}"
          comment: "{{ newvm.role }} {{ newvm.site }} {{ newvm.project }}"
          description: "{{ newvm.role }} {{ newvm.site }} {{ newvm.project }}"
          memory: "{{ newvm.memory }}"
          cpu_cores: "{{ newvm.cpu_cores }}"
          cluster: "{{ newvm.cluster | default(createvm_default.cluster) }}"
          template: "{{ newvm.template | default(createvm_default.template) }}"
          ipv4_address: "{{ newvm.ipv4.address }}"
          ipv4_netmask: "{{ newvm.ipv4.netmask }}"
          ipv4_gateway: "{{ newvm.ipv4.gateway }}"
          nics:
            - name: "{{ newvm.nic.name | default(createvm_default.nic.name) }}"
              network: "{{ newvm.nic.network | default(createvm_default.nic.network) }}"
              profile_name: "{{ newvm.nic.profile_name | default(createvm_default.nic.profile_name) }}"
          ci:
            hostname: "{{ newvm.hostname | default(newvm.site + newvm.role + newvm.suffix | string) }}"
            username: "{{ ansible_user }}"
            userpass: "{{ ansible_password }}"
            pubkey: "{{ ansible_ssh_public_key }}"
            customscript: "{{ newvm.customscript | default(createvm_default.customscript) }}"
            nic_boot_protocol: "{{ newvm.ipv4.method }}"
            dns_servers: "{{ newvm.dns_servers | default(createvm_default.dns_servers) }}"
            dns_search: "{{ newvm.dns_search | default(createvm_default.dns_search) }}"
          tags:
            - "{{ newvm.template | default(createvm_default.template) }}"
            - "project_{{ newvm.project }}"
            - "site_{{ newvm.site }}"
            - "role_{{ newvm.role }}"
      loop: "{{ newvms }}"
      loop_control:
        loop_var: newvm
        label: "{{ newvm.project }}_{{ newvm.site }}{{ newvm.role }}{{ newvm.suffix | string }}"
