site_gtmadm: 
  hosts:
    ws1: { ansible_host: 10.3.77.112 }
    ws2: { ansible_host: 10.3.77.113 }
    ws3: { ansible_host: 10.3.11.41 }
    ws4: { ansible_host: 10.3.11.42 }
    ws5: { ansible_host: 10.3.11.43 }
    ws6: { ansible_host: 10.3.71.44 }

role_dc:
  children:
    first_dc:
      hosts:
        gpdc1:
  hosts:
    gpdc2:

role_ws:
  hosts:
    gpws1:

os_windows:
  hosts:
    ws1:
    ws2:
    ws3:
    ws4:
    ws5:
    ws6:

os_redos:
  hosts:

project_gtm:
  children:
    site_gtmadm:
