---
# tasks file for interfaces
#
- name: Configure VLANs 
  routeros_command:
    commands:
      - /interface vlan add name="vlan{{ item.vlan_id }}" interface="{{ item.interface }}" comment="To {{ item.name }}" vlan-id="{{ item.vlan_id }}" 
  when:
    - vlans is defined
  loop: "{{ vlans }}"
  tags:
    - vlans

- name: Create Loopbacks
  routeros_command:
    commands:
      - /interface bridge add name="{{ item.routeros_if }}" comment="{{ item.desc }}"
  when: 
    - item.routeros_if is match('loopback.*')
  loop: "{{ interfaces }}"
  tags:
    - loopback


- name: Configure interfaces
  routeros_command:
    commands:
      - /interface set comment="{{ item.desc }}" [find where name="{{ item.routeros_if }}"]
  loop: "{{ interfaces }}"
  tags:
    - interfaces

- name: Configure IPv4 addressing
  routeros_command:
    commands:
      - /ip address add interface="{{ item.routeros_if }}" address="{{ item.ipv4 }}" comment="{{ item.desc }}"
  when:
    - item.ipv4 is defined
    - '"dhcp" not in item.ipv4'
  loop: "{{ interfaces }}"
  tags:
    - ipv4


- name: Configure IPv4 addressing - DHCP
  routeros_command:
    commands:
      - /ip dhcp-client add interface="{{ item.routeros_if }}" disabled=no comment="{{ item.desc }}" 
  when:
    - item.ipv4 is defined
    - '"dhcp" in item.ipv4'
  loop: "{{ interfaces }}"
  tags:
    - ipv4

- name: Configure IPv6 addressing
  routeros_command:
    commands:
      - /ipv6 address add interface="{{ item.routeros_if }}" address="{{ item.ipv6 }}" comment="{{ item.desc }}"
  when: item.ipv6 is defined
  loop: "{{ interfaces }}"
  tags:
    - ipv6

- name: Interface cleanup
  routeros_command:
    commands:
      - /ip address remove [find where invalid]
  tags:
    - ipv4
    - ipv6
