---
# defaults file for preconfig
preconfig_selinux: disabled
preconfig_installpackages: true
preconfig_graphicaltarget: false

preconfig_packages:
- tmux
- ansible
- chrony
- python3-libselinux
- glibc-langpack-en
- realmd
- sssd
- oddjob
- oddjob-mkhomedir
- adcli
- join-to-domain
- samba-client
- samba-common.noarch
- samba-common
- samba-libs
- samba-winbind
- krb5-workstation
- samba-winbind-krb5-locator
- openldap-clients

preconfig_timezone: Europe/Moscow
